# Generated by Django 3.2.7 on 2021-09-25 02:40

from django.db import migrations, models
import django.db.models.deletion
import timeliner.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timeliner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeliner',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to=timeliner.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='timeliner',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to=timeliner.models.image_directory_path),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.CharField(blank=True, max_length=25, null=True)),
                ('longitude', models.CharField(blank=True, max_length=25, null=True)),
                ('road', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('mapurl', models.URLField(blank=True, null=True)),
                ('timeliner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timeliner.timeliner')),
            ],
        ),
    ]
