# Generated by Django 3.2.7 on 2021-09-26 11:28

from django.db import migrations, models
import timeliner.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeliner', '0003_auto_20210925_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeliner',
            name='image_one',
            field=models.ImageField(blank=True, default='', null=True, upload_to=timeliner.models.image_directory_path),
        ),
    ]
