# Generated by Django 3.2.7 on 2021-09-26 11:30

from django.db import migrations, models
import pathlib
import timeliner.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeliner', '0004_alter_timeliner_image_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeliner',
            name='image_one',
            field=models.ImageField(blank=True, default=pathlib.PureWindowsPath('D:/Dev/django/x-map/x-map-backend/x_map/uploads/images/def.jpg'), null=True, upload_to=timeliner.models.image_directory_path),
        ),
    ]
