# Generated by Django 3.2.7 on 2021-09-26 11:33

from django.db import migrations, models
import timeliner.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeliner', '0005_alter_timeliner_image_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeliner',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to=timeliner.models.image_directory_path),
        ),
    ]
